#!/usr/bin/env python
# encoding: utf-8
"""
meepmeep.py

Created by Pushkar Modi on 2010-10-03.
"""

#Input specifications

#The input file will contain ASCII text that is going to be completely ignored by your program. 
# In fact, do not even bother opening up the file, it will just complicate things. The input file 
# format is as follows:
#<Lots of ASCII characters that do not matter>
#
#Example input file:
#Just ignore me, I am not important.

#Output specifications

# The output should be the string "Meep meep!" (without the double quotes, using exact capitalization) 
# followed by a single newline (don't forget this part!). 
#
# Example output (newline after string):
# Meep meep!

import sys

def main(inputFile):
	print "Meep meep!"

if __name__ == '__main__':
	main(sys.argv)